[tool.poetry]
name = "football-analytics"
version = "0.1.0"
description = ""
authors = ["Tu Nombre <tu@email.com>"]

package-mode = false

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.dev-dependencies]
# aquí puedes poner las dependencias para desarrollo, si quieres
